apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubernetes-emptydir-rs
spec:
  replicas : 2
  selector :
    matchLabels :
      app : webserver
  template :
    metadata :
      name : emptydir-pod
      labels :
        app : webserver
    spec : 
      containers:
      - name : webserver
        image: nginx:alpine
        ports :
        - containerPort : 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: emptydir-vol
          readOnly : true
      
      - name : contents-creator
        image : ghcr.io/c1t1d0s7/fortune
        volumeMounts:
        - mountPath : /var/htdocs
          name : emptydir-vol
          readOnly : false
      
      volumes:
      - name: emptydir-vol
        emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  selector:
    app: webserver
  type: LoadBalancer
  ports : 
  - protocol : TCP
    port : 80
    targetPort : 80
