apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app : kibana
spec:
  replicas: 3
  selector:
    matchLabels:
     app : kibana
  template:
    metadata:
      labels:
        app : kibana
    spec:
      containers:
      - name: kibana
        image: elastic/kibana:6.4.0
        env:
        - name: SERVER_NAME
          value: "kibana.kubernetes.example.com"
        - name: ELASTICSEARCH_URL
          #SVC_NAME.NAMESPACE.svc.cluster.local:Port
          value: "http://elasticsearch-svc.elastic-stack.svc.cluster.local:9200"
        ports:
        - name: kibana
          containerPort: 5601
---
apiVersion : v1
kind : Service
metadata :
  name : kibana-svc
  namespace : elastic-stack
spec :
  selector :
    app : kibana
  type : NodePort
  ports :
  - name : kibana
    port : 5601
    targetPort : 5601
    nodePort : 30561
