apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: nginx-default
  volumes:
    - name: nginx-default
      persistentVolumeClaim:
        claimName: pvc-hostpath
